### ISSUE TITLE
Is there something specific to do when using notif/notify?

### ISSUE THREAD

**Issue by Keagel** [Wykerd/bazcal#10]
For some reason I'm always getting the message "Looks like the market is in flames" meaning there are no results. However, `advise` works fine with the same given amount.

**Comment by Wykerd** [comment]
oof I'll check this out :+1:

**Comment by Keagel** [comment]
I should however note that your hosted version works.

**Comment by Wykerd** [comment]
Yes but that's running release 4.0.0 not master

**Comment by Wykerd** [comment]
Most likely the changes that @Jakkalsie made when refactoring, I'll get on this issue as soon as possible!

**Comment by Wykerd** [comment]
Yep it's the include_stability filter in advise thats broken

**Comment by Wykerd** [comment]
Should be fixed now in new commit ab98a44

**Comment by Keagel** [comment]
Can confirm it's fixed!
